"""empty message

Revision ID: 4bcf0ced6e98
Revises: 89300552035e
Create Date: 2024-10-24 03:29:29.266964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcf0ced6e98'
down_revision = '89300552035e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viaje_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_email', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('grupos_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'viajes', ['viaje_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_email'], ['email'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grupos_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_email')
        batch_op.drop_column('viaje_id')

    # ### end Alembic commands ###
