"""empty message

Revision ID: 5402a695776f
Revises: b8587772d5b4
Create Date: 2024-10-18 19:23:13.034311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5402a695776f'
down_revision = 'b8587772d5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('presupuesto_grupo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('motivo', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('nota', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('nota')
        batch_op.drop_column('motivo')
        batch_op.drop_column('presupuesto_grupo')
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    # ### end Alembic commands ###
