"""empty message

Revision ID: 645d5c748651
Revises: 3484aa3a554d
Create Date: 2024-10-07 13:16:28.088089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645d5c748651'
down_revision = '3484aa3a554d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('number', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('more_info', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('more_info')
        batch_op.drop_column('number')
        batch_op.drop_column('username')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
