"""empty message

<<<<<<<< HEAD:migrations/versions/2d353ed32a82_.py
Revision ID: 2d353ed32a82
Revises: 
Create Date: 2024-10-20 14:40:46.266276
========
Revision ID: 693f3ed4a4aa
Revises: 
Create Date: 2024-10-21 22:42:37.156596
>>>>>>>> d8f1072170ff272e6ba0b5ad7cda9f963b5b6840:migrations/versions/693f3ed4a4aa_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/2d353ed32a82_.py
revision = '2d353ed32a82'
========
revision = '693f3ed4a4aa'
>>>>>>>> d8f1072170ff272e6ba0b5ad7cda9f963b5b6840:migrations/versions/693f3ed4a4aa_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('number', sa.String(length=120), nullable=False),
    sa.Column('more_info', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_image_url', sa.String(length=360), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destino', sa.String(length=120), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('presupuesto_grupo', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=120), nullable=True),
    sa.Column('nota', sa.String(length=120), nullable=True),
    sa.Column('presupuesto_personal', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_actividad', sa.String(length=120), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=120), nullable=True),
    sa.Column('imagenes', sa.String(length=360), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('viaje_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=360), nullable=True),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_actividad')
    )
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=120), nullable=False),
    sa.Column('viaje_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividades_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['actividades_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividades_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actividades_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('group_association')
    op.drop_table('comentarios')
    op.drop_table('grupos')
    op.drop_table('actividades')
    op.drop_table('viajes')
    op.drop_table('users')
    # ### end Alembic commands ###
