"""empty message

<<<<<<<< HEAD:migrations/versions/de8a1ec3af1e_.py
Revision ID: de8a1ec3af1e
Revises: 
Create Date: 2024-10-29 20:40:31.461114
========
Revision ID: 9210ca83237b
Revises: 
Create Date: 2024-10-29 20:39:14.232247
>>>>>>>> d3868319daf9a04b6ff31abe80d0b7ba30cf2681:migrations/versions/9210ca83237b_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/de8a1ec3af1e_.py
revision = 'de8a1ec3af1e'
========
revision = '9210ca83237b'
>>>>>>>> d3868319daf9a04b6ff31abe80d0b7ba30cf2681:migrations/versions/9210ca83237b_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('salt', sa.String(length=80), nullable=False),
    sa.Column('more_info', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_image_url', sa.String(length=360), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destino', sa.String(length=120), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('presupuesto_grupo', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=120), nullable=True),
    sa.Column('presupuesto_personal', sa.String(length=120), nullable=True),
    sa.Column('nota', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_image_url', sa.String(length=360), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_actividad', sa.String(length=120), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('imagenes', sa.String(length=360), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('viaje_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=360), nullable=True),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viaje_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividades_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['actividades_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividades_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actividades_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('group_association')
    op.drop_table('comentarios')
    op.drop_table('grupos')
    op.drop_table('actividades')
    op.drop_table('viajes')
    op.drop_table('users')
    # ### end Alembic commands ###
