"""empty message

Revision ID: 9fae8e36c3b8
Revises: eb74d958750d
Create Date: 2024-10-22 22:40:38.264325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fae8e36c3b8'
down_revision = 'eb74d958750d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('grupos_viaje_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('viaje_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viaje_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grupos_viaje_id_fkey', 'viajes', ['viaje_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
