"""empty message

Revision ID: b8587772d5b4
Revises: 48ff91b4736b
Create Date: 2024-10-14 14:55:50.566845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8587772d5b4'
down_revision = '48ff91b4736b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_actividad', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('actividades_activity_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['nombre_actividad'])
        batch_op.drop_column('activity_name')

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actividades_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comentarios_activity_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'actividades', ['actividades_id'], ['id'])
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comentarios_activity_id_fkey', 'actividades', ['activity_id'], ['id'])
        batch_op.drop_column('actividades_id')

    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('actividades_activity_name_key', ['activity_name'])
        batch_op.drop_column('nombre_actividad')

    # ### end Alembic commands ###
