"""empty message

Revision ID: c48ae94c17af
Revises: 4510e7283526
Create Date: 2024-10-23 00:59:16.890154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c48ae94c17af'
down_revision = '4510e7283526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('grupos_viaje_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('viaje_id')

    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('fecha_fin',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('presupuesto_personal',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('nota',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('presupuesto_personal',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('fecha_fin',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viaje_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grupos_viaje_id_fkey', 'viajes', ['viaje_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
