"""empty message

Revision ID: daa3ad14d22d
Revises: de53d4277ee9
Create Date: 2024-10-26 01:36:47.980673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa3ad14d22d'
down_revision = 'de53d4277ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_constraint('actividades_nombre_actividad_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.create_unique_constraint('actividades_nombre_actividad_key', ['nombre_actividad'])

    # ### end Alembic commands ###
