"""empty message

Revision ID: eb74d958750d
Revises: 9b8408ffafcc
Create Date: 2024-10-22 22:16:08.635873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb74d958750d'
down_revision = '9b8408ffafcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presupuesto_personal', sa.String(length=120), nullable=True))
        batch_op.drop_column('presupuestovo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presupuestovo', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('presupuesto_personal')

    # ### end Alembic commands ###
